domains:
- domain: hooli.holistics.io
  type: PRIMARY
ingress:
  rules:
  - component:
      name: hooli
    match:
      path:
        prefix: /
name: hooli
region: sgp
services:
- http_port: 3000
  image:
    registry: ghcr.io
    registry_credentials: EV[1:SRRbLgS/AcdC/03PK0t/uBKkSb5zPOML:UwlESxx9FIdgKE7oeRsrhFG7c0HxSRzdquBQnS7zSzRRKhJC6J8CMcR8klvaT6UvVX4aR/v8JSXpfDuW6nv3vdiQUEVdnepd6sotKzf0gw==]
    registry_type: GHCR
    repository: holistics/hooli
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: hooli
