domains:
- domain: hooli.getholistics.com
  type: ALIAS
ingress:
  rules:
  - component:
      name: hooli
    match:
      path:
        prefix: /
name: hooli
region: sgp
services:
- http_port: 3000
  image:
    registry: ghcr.io
    registry_credentials: EV[1:f8mafOx07TBpvxrCYRZ5nwpjLL8VCBo2:BbulNVqv7UprIB+utMKUZz2StOH7fanDPfF7ukkAe/LO46Zsx/X+LnpCg107sAJzPWMvHLlo4ivQ+eKOkk64og==]
    registry_type: GHCR
    repository: holistics/hooli
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: hooli
