name: hooli
services:
- name: hooli
  image:
    registry: ghcr.io
    registry_credentials: EV[1:zVFVjnIU7NEGyAT6QfxeLEbshkdsm7Jb:WUVBhu/5mRvjhdoSWnrFS5SYM50UFtO0BDx0O3vLev206E5Gq0plibuRUVdkRESjDlMev1oFHqfvSZ6AxbWKTQ==]
    registry_type: GHCR
    repository: holistics/hooli
    tag: latest