name: hooli
services:
- name: hooli
  image:
    registry: ghcr.io
    registry_credentials: EV[1:r40Yk/+/t1vyGsIniuioO11oI/joicDa:p6XWR3avDlpBtnu/2PEb/0+xdLxJVFCDJNrXTNMTuSgsRcdvbQETEu1gnsBa0zgnyPH4l/VkTycuYaszSYNmeg==]
    registry_type: GHCR
    repository: holistics/hooli
    tag: latest